---
title: "R Notebook"
output: html_notebook
---

```{r libraries}
require(tidyverse)

```

```{r q1}
?sample.int
qplot(as.factor(sample.int(2, size = 10, replace = TRUE)))
qplot(as.factor(sample.int(3, size = 10, replace = TRUE)))
```

```{r beta}
rbeta(5, 3, 3)

pl.beta <- function(a,b, asp = if(isLim) 1, ylim = if(isLim) c(0,1.1)) {
  if(isLim <- a == 0 || b == 0 || a == Inf || b == Inf) {
    eps <- 1e-10
    x <- c(0, eps, (1:7)/16, 1/2+c(-eps,0,eps), (9:15)/16, 1-eps, 1)
  } else {
    x <- seq(0, 1, length = 1025)
  }
  fx <- cbind(dbeta(x, a,b), pbeta(x, a,b), qbeta(x, a,b))
  f <- fx; f[fx == Inf] <- 1e100
  matplot(x, f, ylab="", type="l", ylim=ylim, asp=asp,
          main = sprintf("[dpq]beta(x, a=%g, b=%g)", a,b))
  abline(0,1,     col="gray", lty=3)
  abline(h = 0:1, col="gray", lty=3)
  legend("top", paste0(c("d","p","q"), "beta(x, a,b)"),
         col=1:3, lty=1:3, bty = "n")
  invisible(cbind(x, fx))
}
pl.beta(3,2)
```


## Dirichlet

```{r dirichlet}
require(gtools)
rdirichlet(10, c(0.3, 0.3, 0.3))
rdirichlet(10, c(3, 3, 2))

```


## Gamma
```{r gamma}
rgamma(10, 3, 1)
?rgamma
```


## GAUSS
```{r gauss}
library(MASS)
NUM = 10
DIM = 5

mu = rep(0, DIM)
Sigma = diag(DIM)
Sigma

mgauss = mvrnorm(NUM, mu, Sigma)
mgauss

```


## Caussy

```{r caussy}
rcauchy(10)
```



# Q3
- y1 ~ norm(50,20)
- y2 ~ norm(20,15)
- y = y1 - y2 ~ norm(30,25 <- sqrt(20*20 + 15*15))

```{r randdom}
y1 = rnorm(2000, 50, 20)
y2 = rnorm(2000, 20, 15)
y = y1-y2
qplot(y)
mean(y)
sd(y)

```

# Q4
```{r q4}
#install.packages("gamlss.dist")
require(gamlss.dist)
plot(function(y) dSICHEL(y, mu=10, sigma = 0.1 , nu=1 ), from=0, to=30, n=30+1, type="h") # pdf
# cdf plot
PPP <- par(mfrow=c(2,1))
plot(function(y) pSICHEL(y, mu=10, sigma =0.1, nu=1 ), from=0, to=30, n=30+1, type="h") # cdf
cdf<-pSICHEL(0:30, mu=10, sigma=0.1, nu=1)
sfun1 <- stepfun(1:30, cdf, f = 0)
plot(sfun1, xlim=c(0,30), main="cdf(x)")
par(PPP)

```

```{r}
n = 10
rBCT(n, mu = 5, sigma = 0.1, nu = 1, tau = 2)

plot(function(y) dBCT(y, mu=10, sigma = 0.1 , nu=1,tau=2 ), from=0, to=30, n=30+1, type="h") # pdf

```
























