---
title: "R Notebook"
output: html_notebook
---

```{r libraries}
require(tidyverse)
require(rstan)
require(gridExtra)

```

```{r data}
student = read.csv("https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap08/input/data-attendance-4-1.txt")
attendance = read.csv("https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap08/input/data-attendance-4-2.txt")
student
attendance
```

# attendance rates

## by student
- plot the attendance rate for each student
```{r student}
attendance_rate = attendance %>%
        group_by(PersonID) %>%
        summarise(attendance_rate = mean(Y))

student = left_join(student, attendance_rate)
student
qplot(student$attendance_rate)

```


## by subject
```{r subject}
course_attendance = attendance %>%
        group_by(CourseID) %>%
        summarise(course_attendance = mean(Y))

qplot(course_attendance$course_attendance)

```

# 8.8
```{r 8-8}
d1 = read.csv("https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap08/input/data-attendance-4-1.txt")
d2 = read.csv("https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap08/input/data-attendance-4-2.txt")
N <- 50
C <- 10
I <- nrow(d2)
conv <- c(0, 0.2, 1)
names(conv) <- c('A', 'B', 'C')
data <- list(N=N, C=C, I=I, A=d1$A, Score=d1$Score/200,
  PID=d2$PersonID, CID=d2$CourseID, W=conv[d2$Weather], Y=d2$Y)
fit <- stan(file='model/model8-8.stan', data=data,
  pars=c('b', 'b_P', 'b_C', 's_P', 's_C', 'q'), seed=1234)

```
```{r ROC}
library(pROC)

ms <- rstan::extract(fit)
N_mcmc <- length(ms$lp__)
spec <- seq(from=0, to=1, len=201)
probs <- c(0.1, 0.5, 0.9)

auces <- numeric(N_mcmc)
m_roc <- matrix(nrow=length(spec), ncol=N_mcmc)
for (i in 1:N_mcmc) {
  roc_res <- roc(d2$Y, ms$q[i,])
  auces[i] <- as.numeric(roc_res$auc)
  m_roc[,i] <- coords(roc_res, x=spec, input='specificity', ret='sensitivity')
}
quantile(auces, prob=probs)

```



# Stan
```{r stan}
d1 = read.csv("https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap08/input/data-attendance-4-1.txt")
d2 = read.csv("https://raw.githubusercontent.com/MatsuuraKentaro/RStanBook/master/chap08/input/data-attendance-4-2.txt")
N <- 50
C <- 10
I <- nrow(d2)
d_conv <- data.frame(X=c(0, 0.2, 1))
rownames(d_conv) <- c('A', 'B', 'C')
data <- list(N=N, C=C, I=I, A=d1$A, Score=d1$Score/200,
  PID=d2$PersonID, CID=d2$CourseID, W=d_conv[d2$Weather, ], Y=d2$Y)
fit <- stan(file="model/model8-9.stan", data=data,
  pars=c('b', 'b_P', 'b_C', 'q'), seed=1234)

```

```{r ms}

fit


```

